version: '3.3'
services:
  nc-start-db:
    container_name: go-start-db
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
