version: '3.3'
services:

  go-start:
    image: go-start
    container_name: go-start-container
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - go-start-db
    restart: always

  go-start-db:
    container_name: go-start-db
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"