port: "8080"
db:
#  host: go-start-db
#  port: 5432
  host: localhost
  port: 54321
  username: postgres
  name: postgres
  url: postgres://postgres:postgres@localhost:54321/postgres?sslmode=disable
  migration: file://schema
